# Generated by Django 5.2.6 on 2025-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
