# Generated by Django 5.2.6 on 2025-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_complaint_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('water', 'Water Leakage'), ('road', 'Broken Road/Potholes'), ('garbage', 'Garbage Collection'), ('electricity', 'Electricity Issues'), ('sewage', 'Sewage Problems'), ('parks', 'Park Maintenance'), ('streetlights', 'Street Light Issues'), ('traffic', 'Traffic Problems'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
