# Generated by Django 5.2.6 on 2025-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_complaint_category_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank='true', default='complaint_photos/default.jpg', upload_to=''),
        ),
    ]
