# Generated by Django 5.2.6 on 2025-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_complaint_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, default='complaint_photos/default.jpg', null=True, upload_to='complaint_photos/'),
        ),
    ]
