# Generated by Django 5.2.6 on 2025-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_complaint_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(default='complaint_photos/default.jpg', upload_to='complaint_photos/'),
        ),
    ]
