# Generated by Django 5.2.6 on 2025-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_complaint_report_id_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='report_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
