# Generated by Django 5.2.6 on 2025-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_complaint_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='report_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
