# Generated by Django 5.2.6 on 2025-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_complaint_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('water', 'Water Leakage'), ('road', 'Broken Road/Potholes'), ('garbage', 'Garbage Collection'), ('electricity', 'Electricity Issues'), ('sewage', 'Sewage Problems'), ('parks', 'Park Maintenance'), ('streetlights', 'Street Light Issues'), ('traffic', 'Traffic Problems'), ('other', 'Other')], max_length=100),
        ),
    ]
