# Generated by Django 5.2.6 on 2025-10-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(choices=[('water', 'Water Leakage'), ('road', 'Broken Road/Potholes'), ('garbage', 'Garbage Collection'), ('electricity', 'Electricity Issues'), ('sewage', 'Sewage Problems'), ('parks', 'Park Maintenance'), ('streetlights', 'Street Light Issues'), ('traffic', 'Traffic Problems'), ('other', 'Other')], max_length=100)),
                ('area_assigned', models.CharField(blank=True, help_text="e.g., 'North Zone', 'Sector 5', 'All'", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='user.contractor'),
        ),
    ]
