# Generated by Django 5.2.6 on 2025-10-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_contractor_remove_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={},
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('water', 'Water Leakage'), ('road', 'Broken Road/Potholes'), ('garbage', 'Garbage Collection'), ('electricity', 'Electricity Issues'), ('sewage', 'Sewage Problems'), ('parks', 'Park Maintenance'), ('streetlights', 'Street Light Issues'), ('traffic', 'Traffic Problems'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='report_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='area_assigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
